####################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
####################################################################################################


# Following properties are mandatory when engine files are not specified:
#   int8-calib-file(Only in INT8)
#   Caffemodel mandatory properties: model-file, proto-file, output-blob-names
#   UFF: uff-file, input-dims, uff-input-blob-name, output-blob-names
#   ONNX: onnx-file
#
# Mandatory properties for detectors:
#   num-detected-classes
#
# Optional properties for detectors:
#   cluster-mode(Default=Group Rectangles), interval(Primary mode only, Default=0)
#   custom-lib-path,
#   parse-bbox-func-name
#
# Mandatory properties for classifiers:
#   classifier-threshold, is-classifier, classifier-type
#
# Optional properties for classifiers:
#   classifier-async-mode(Secondary mode only, Default=false)
#
# Optional properties in secondary mode:
#   operate-on-gie-id(Default=0), operate-on-class-ids(Defaults to all classes),
#   input-object-min-width, input-object-min-height, input-object-max-width,
#   input-object-max-height
#
# Following properties are always recommended:
#   batch-size(Default=1)
#
# Other optional properties:
#   net-scale-factor(Default=1), network-mode(Default=0 i.e FP32),
#   model-color-format(Default=0 i.e. RGB) model-engine-file, labelfile-path,
#   mean-file, gie-unique-id(Default=0), offsets, process-mode (Default=1 i.e. primary),
#   custom-lib-path, network-mode(Default=0 i.e FP32)
#
# The values in the config file are overridden by values set through GObject
# properties.

property:
  gpu-id: 0
  net-scale-factor: 1
  tlt-model-key: tlt_encode
  tlt-encoded-model: ../../models/Secondary_VehicleTypes/resnet18_vehicletypenet.etlt
  model-engine-file: ../../models/Secondary_VehicleTypes/resnet18_vehicletypenet.etlt_b16_gpu0_int8.engine
  int8-calib-file: ../../models/Secondary_VehicleTypes/cal_trt.bin
  labelfile-path: ../../models/Secondary_VehicleTypes/labels.txt
  force-implicit-batch-dim: 1
  batch-size: 16
  model-color-format: 1
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 1
  network-type: 1
  process-mode: 2
  uff-input-blob-name: input_1
  output-blob-names: predictions/Softmax
  classifier-async-mode: 1
  classifier-threshold: 0.51
  input-object-min-width: 128
  input-object-min-height: 128
  operate-on-gie-id: 1
  operate-on-class-ids: 0
  classifier-type: vehicletype
  #scaling-filter=0
  #scaling-compute-hw=0
  infer-dims: 3;224;224