####################################################################################################
# SPDX-FileCopyrightText: Copyright (c) 2022-2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.
####################################################################################################

property:
  gpu-id: 0
  net-scale-factor: 0.00392156862745098
  tlt-model-key: tlt_encode
  tlt-encoded-model: ../../models/Primary_Detector/resnet18_trafficcamnet.etlt
  model-engine-file: ../../models/Primary_Detector/resnet18_trafficcamnet.etlt_b30_gpu0_int8.engine
  labelfile-path: ../../models/Primary_Detector/labels.txt
  int8-calib-file: ../../models/Primary_Detector/cal_trt.bin
  batch-size: 30
  process-mode: 1
  model-color-format: 0
  ## 0=FP32, 1=INT8, 2=FP16 mode
  network-mode: 1
  num-detected-classes: 4
  interval: 0
  gie-unique-id: 1
  uff-input-order: 0
  uff-input-blob-name: input_1
  output-blob-names: output_cov/Sigmoid;output_bbox/BiasAdd
  force-implicit-batch-dim: 1
  #parse-bbox-func-name: NvDsInferParseCustomResnet
  #custom-lib-path: /path/to/this/directory/libnvds_infercustomparser.so
  ## 1=DBSCAN, 2=NMS, 3= DBSCAN+NMS Hybrid, 4 = None(No clustering)
  cluster-mode: 2
  #scaling-filter: 0
  #scaling-compute-hw: 0
  infer-dims: 3;544;960

#Use the config params below for dbscan clustering mode
#class-attrs-all:
  #detected-min-w: 4
  #detected-min-h: 4
  #minBoxes: 3

#Use the config params below for NMS clustering mode
class-attrs-all:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.2

## Per class configurations
class-attrs-0:
  topk: 20
  nms-iou-threshold: 0.5
  pre-cluster-threshold: 0.4

#class-attrs-1:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5

#class-attrs-2:
  #pre-cluster-threshold: 0.1
  #eps: 0.6
  #dbscan-min-score: 0.95

#class-attrs-3:
  #pre-cluster-threshold: 0.05
  #eps: 0.7
  #dbscan-min-score: 0.5
